START TRANSACTION;

CREATE TABLE users(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'manager', 'user') DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE user_logs (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    activity VARCHAR(255),
    FOREIGN KEY (userID) REFERENCES users(ID) ON DELETE CASCADE
);

CREATE TABLE user_pos (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    position VARCHAR(255),
    FOREIGN KEY (userID) REFERENCES users(ID) ON DELETE CASCADE
);

CREATE TABLE user_session (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    sessionTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES users(ID) ON DELETE CASCADE
);

CREATE TABLE user_alert_history (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    AlertHistory VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES users(ID) ON DELETE CASCADE
);

COMMIT;