START TRANSACTION;

CREATE TABLE users(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'manager', 'user') DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE userLogs (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    activity VARCHAR(255),
    FOREIGN KEY (userID) REFERENCES users(ID) ON DELETE CASCADE
);

CREATE TABLE userPOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    position VARCHAR(255),
    FOREIGN KEY (userID) REFERENCES users(ID) ON DELETE CASCADE
);
COMMIT;